name: fed
channels:
  - pytorch
  - nvidia
  - conda-forge

dependencies:
  - python=3.10
  - pip
  - pytorch
  - torchvision
  - torchaudio
  - pytorch-cuda=12.1
  - numpy
  - scipy
  - scikit-learn
  - scikit-image
  - pandas
  - matplotlib
  - seaborn
  - pillow
  - tqdm
  - opencv
  - black
  - jupyterlab
  - ipywidgets

  - pip:
      - flwr==1.23
      - mlflow